# Generated by Django 4.0.5 on 2022-06-30 12:29

from django.db import migrations, models
import django.db.models.deletion
import invoicing.invoices.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, verbose_name='title')),
                ('number', models.CharField(blank=True, default=invoicing.invoices.models.get_invoice_number, max_length=100, unique=True, verbose_name='number')),
                ('payment_term', models.IntegerField(blank=True, choices=[(14, '14 days'), (30, '30 days'), (60, '60 days')], default=30, verbose_name='payment term')),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='due date')),
                ('currency', models.CharField(blank=True, choices=[('€', 'EUR'), ('C', 'CHF'), ('$', 'USD')], default='€', max_length=1, verbose_name='currency')),
                ('amount_vat', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='amount vat')),
                ('exemption_vat', models.BooleanField(default=False, max_length=100, verbose_name='exemption vat')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('status', models.IntegerField(blank=True, choices=[(1, 'Current'), (2, 'Email sent'), (3, 'Overdue'), (4, 'Paid')], default=1, verbose_name='status')),
                ('slug', models.SlugField(blank=True, max_length=100, null=True, unique=True, verbose_name='slug')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='date of last update')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='clients.client', verbose_name='client')),
            ],
            options={
                'verbose_name': 'invoice',
                'verbose_name_plural': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=1, null=True, verbose_name='quantity')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='invoices.invoice', verbose_name='invoice')),
                ('price', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.price', verbose_name='unit price')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_lines', to='products.product', verbose_name='product')),
            ],
            options={
                'verbose_name': 'invoice line',
                'verbose_name_plural': 'invoice lines',
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='products',
            field=models.ManyToManyField(related_name='invoices', through='invoices.InvoiceLine', to='products.product'),
        ),
    ]
