# Generated by Django 4.0.5 on 2022-06-30 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceline',
            name='price',
        ),
        migrations.AddField(
            model_name='invoiceline',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='date of addition'),
        ),
    ]
