# Generated by Django 4.0.5 on 2022-06-29 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='unit price')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True, verbose_name='slug')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='date of last update')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('name', 'id'),
            },
        ),
    ]
