# Generated by Django 4.0.5 on 2022-06-30 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True, verbose_name='slug')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='date of last update')),
            ],
            options={
                'verbose_name': 'product',
                'verbose_name_plural': 'products',
                'ordering': ('name', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='unit price')),
                ('currency', models.CharField(choices=[('€', 'EUR'), ('C', 'CHF'), ('$', 'USD')], default='€', max_length=1, verbose_name='currency')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='date of creation')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='products.product')),
            ],
        ),
    ]
