# Generated by Django 4.0.5 on 2022-06-30 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='price',
            constraint=models.UniqueConstraint(fields=('product', 'currency'), name='product_currency_unicity_constraint'),
        ),
    ]
