# Generated by Django 4.0.5 on 2022-06-30 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_price_options'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='price',
            name='product_currency_unicity_constraint',
        ),
    ]
